import { jsPDF } from "jspdf"
import { Loan, LOAN_PAYMENT_TYPE_LABELS } from "./types"

/**
 * Shared client-side PDF export helpers for the Loan Tracker tabs.
 *
 * Modeled on the Monthly Log export (`src/app/(app)/monthly-log/page.tsx`):
 * plain jsPDF (no autotable), dark header band, zebra rows, an emerald-tinted
 * Total row, and a footer. jsPDF's built-in Helvetica cannot render the ₹
 * glyph, so amounts are formatted as plain en-IN numbers with NO currency
 * prefix (see CLAUDE.md → Security/jsPDF font limitation).
 */

const MARGIN = 14
const ROW_H = 7

function pdfINR(val: number): string {
  return new Intl.NumberFormat("en-IN", { maximumFractionDigits: 0 }).format(val)
}

function shortDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  })
}

function safeFileName(loanName: string, section: string): string {
  const slug = loanName.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "")
  return `Artha-${slug || "Loan"}-${section}.pdf`
}

interface Column {
  label: string
  x: number
  w: number
  align: "left" | "right"
}

/** Draw the title + subtitle block; returns the y where the table should start. */
function drawHeader(doc: jsPDF, title: string, subtitle: string): number {
  doc.setFont("helvetica", "bold")
  doc.setFontSize(16)
  doc.setTextColor(30, 30, 30)
  doc.text(title, MARGIN, 20)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(11)
  doc.setTextColor(80, 80, 80)
  doc.text(subtitle, MARGIN, 28)

  return 38
}

/** Draw the dark column-header band. Returns the y below it. */
function drawColumnHeader(doc: jsPDF, cols: Column[], y: number, colW: number): number {
  doc.setFillColor(30, 30, 30)
  doc.rect(MARGIN, y, colW, 7, "F")
  doc.setFont("helvetica", "bold")
  doc.setFontSize(8)
  doc.setTextColor(255, 255, 255)
  for (const col of cols) {
    const textX = col.align === "right" ? col.x + col.w - 1 : col.x + 1
    doc.text(col.label, textX, y + 5, { align: col.align })
  }
  return y + 7
}

function drawFooter(doc: jsPDF) {
  doc.setFont("helvetica", "normal")
  doc.setFontSize(7)
  doc.setTextColor(160, 160, 160)
  doc.text(
    `Generated by Artha on ${new Date().toLocaleDateString("en-IN")}`,
    MARGIN,
    290
  )
}

// ---------------------------------------------------------------------------
// Payments
// ---------------------------------------------------------------------------

export function exportLoanPaymentsPdf(loan: Loan) {
  const doc = new jsPDF({ unit: "mm", format: "a4" })
  const colW = doc.internal.pageSize.getWidth() - MARGIN * 2

  let y = drawHeader(doc, "Artha — Loan Payments", loan.name)

  const cols: Column[] = [
    { label: "Date", x: MARGIN, w: 24, align: "left" },
    { label: "Type", x: MARGIN + 24, w: 26, align: "left" },
    { label: "Description", x: MARGIN + 50, w: 46, align: "left" },
    { label: "Paid By", x: MARGIN + 96, w: 28, align: "left" },
    { label: "Mode", x: MARGIN + 124, w: 22, align: "left" },
    { label: "Amount", x: MARGIN + 146, w: colW - 146, align: "right" },
  ]

  y = drawColumnHeader(doc, cols, y, colW)

  const payments = [...loan.payments].sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
  )

  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  let total = 0

  payments.forEach((p, idx) => {
    if (y > 270) {
      doc.addPage()
      y = drawColumnHeader(doc, cols, 14, colW)
      doc.setFont("helvetica", "normal")
      doc.setFontSize(8)
    }
    const shade = idx % 2 === 0 ? 255 : 249
    doc.setFillColor(shade, shade, shade)
    doc.rect(MARGIN, y, colW, ROW_H, "F")
    doc.setTextColor(40, 40, 40)

    doc.text(shortDate(p.date), cols[0].x + 1, y + 5)
    doc.text(LOAN_PAYMENT_TYPE_LABELS[p.type], cols[1].x + 1, y + 5)
    doc.text((p.description ?? "—").slice(0, 26), cols[2].x + 1, y + 5)
    doc.text((p.paidBy?.name ?? "—").slice(0, 16), cols[3].x + 1, y + 5)
    doc.text((p.mode ?? "—").slice(0, 12), cols[4].x + 1, y + 5)
    doc.text(pdfINR(Number(p.amount)), cols[5].x + cols[5].w - 1, y + 5, { align: "right" })

    total += Number(p.amount)
    y += ROW_H
  })

  drawTotalRow(doc, y, colW, "Total", pdfINR(total))
  drawFooter(doc)
  doc.save(safeFileName(loan.name, "Payments"))
}

// ---------------------------------------------------------------------------
// EMIs (planned vs paid pivot, one Planned/Paid pair per member)
// ---------------------------------------------------------------------------

const MONTH_ABBR = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
]

export function exportLoanEmisPdf(loan: Loan) {
  const doc = new jsPDF({ unit: "mm", format: "a4" })
  const colW = doc.internal.pageSize.getWidth() - MARGIN * 2

  let y = drawHeader(doc, "Artha — Loan EMIs", loan.name)

  const members = loan.members

  // Build a lookup of "year-month-userId" -> entry, plus the set of months.
  const entryByKey = new Map<string, { planned: number; paid: number | null }>()
  const monthKeys = new Set<string>()
  for (const e of loan.emiEntries) {
    const mKey = `${e.year}-${String(e.month).padStart(2, "0")}`
    monthKeys.add(mKey)
    entryByKey.set(`${mKey}-${e.userId}`, {
      planned: Number(e.plannedShare),
      paid: e.actualPaid != null ? Number(e.actualPaid) : null,
    })
  }
  // Descending month order (newest first) to match the on-screen grid.
  const sortedMonths = Array.from(monthKeys).sort().reverse()

  // Column layout: Month | [member: Planned, Paid] x N | Total Paid
  const monthW = 22
  const totalW = 24
  const perMemberW = (colW - monthW - totalW) / Math.max(1, members.length)
  const pairW = perMemberW / 2

  const cols: Column[] = [{ label: "Month", x: MARGIN, w: monthW, align: "left" }]
  let cx = MARGIN + monthW
  for (const m of members) {
    cols.push({ label: `${m.user.name} Pl.`, x: cx, w: pairW, align: "right" })
    cols.push({ label: `${m.user.name} Paid`, x: cx + pairW, w: pairW, align: "right" })
    cx += perMemberW
  }
  cols.push({ label: "Total Paid", x: cx, w: totalW, align: "right" })

  y = drawColumnHeader(doc, cols, y, colW)

  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)

  // Running per-member column totals + overall paid total.
  const plannedTotals = members.map(() => 0)
  const paidTotals = members.map(() => 0)
  let overallTotalPaid = 0

  sortedMonths.forEach((mKey, idx) => {
    if (y > 270) {
      doc.addPage()
      y = drawColumnHeader(doc, cols, 14, colW)
      doc.setFont("helvetica", "normal")
      doc.setFontSize(8)
    }
    const shade = idx % 2 === 0 ? 255 : 249
    doc.setFillColor(shade, shade, shade)
    doc.rect(MARGIN, y, colW, ROW_H, "F")
    doc.setTextColor(40, 40, 40)

    const [yr, mo] = mKey.split("-").map(Number)
    doc.text(`${MONTH_ABBR[mo - 1]} ${yr}`, cols[0].x + 1, y + 5)

    let monthTotal = 0
    members.forEach((m, mi) => {
      const e = entryByKey.get(`${mKey}-${m.userId}`)
      const plannedCol = cols[1 + mi * 2]
      const paidCol = cols[2 + mi * 2]
      const planned = e ? e.planned : null
      const paid = e ? e.paid : null
      doc.text(planned != null ? pdfINR(planned) : "—", plannedCol.x + plannedCol.w - 1, y + 5, { align: "right" })
      doc.text(paid != null ? pdfINR(paid) : "—", paidCol.x + paidCol.w - 1, y + 5, { align: "right" })
      if (planned != null) plannedTotals[mi] += planned
      if (paid != null) paidTotals[mi] += paid
      // Month total mirrors the grid: actualPaid when present, else plannedShare.
      if (e) monthTotal += paid != null ? paid : planned!
    })
    const totalCol = cols[cols.length - 1]
    doc.text(monthTotal > 0 ? pdfINR(monthTotal) : "—", totalCol.x + totalCol.w - 1, y + 5, { align: "right" })
    overallTotalPaid += monthTotal
    y += ROW_H
  })

  // Total row: per-member Planned/Paid sums + overall total paid.
  if (y > 270) {
    doc.addPage()
    y = 14
  }
  doc.setFillColor(220, 240, 225)
  doc.rect(MARGIN, y, colW, 8, "F")
  doc.setFont("helvetica", "bold")
  doc.setFontSize(8)
  doc.setTextColor(20, 80, 40)
  doc.text("Total", cols[0].x + 1, y + 5.5)
  members.forEach((_, mi) => {
    const plannedCol = cols[1 + mi * 2]
    const paidCol = cols[2 + mi * 2]
    doc.text(pdfINR(plannedTotals[mi]), plannedCol.x + plannedCol.w - 1, y + 5.5, { align: "right" })
    doc.text(pdfINR(paidTotals[mi]), paidCol.x + paidCol.w - 1, y + 5.5, { align: "right" })
  })
  const totalCol = cols[cols.length - 1]
  doc.text(pdfINR(overallTotalPaid), totalCol.x + totalCol.w - 1, y + 5.5, { align: "right" })

  drawFooter(doc)
  doc.save(safeFileName(loan.name, "EMIs"))
}

// ---------------------------------------------------------------------------
// Disbursements
// ---------------------------------------------------------------------------

export function exportLoanDisbursementsPdf(loan: Loan) {
  const doc = new jsPDF({ unit: "mm", format: "a4" })
  const colW = doc.internal.pageSize.getWidth() - MARGIN * 2

  let y = drawHeader(doc, "Artha — Loan Disbursements", loan.name)

  const cols: Column[] = [
    { label: "Date", x: MARGIN, w: 30, align: "left" },
    { label: "Notes", x: MARGIN + 30, w: colW - 30 - 40, align: "left" },
    { label: "Amount", x: MARGIN + colW - 40, w: 40, align: "right" },
  ]

  y = drawColumnHeader(doc, cols, y, colW)

  const disbursements = [...loan.disbursements].sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
  )

  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  let total = 0

  disbursements.forEach((d, idx) => {
    if (y > 270) {
      doc.addPage()
      y = drawColumnHeader(doc, cols, 14, colW)
      doc.setFont("helvetica", "normal")
      doc.setFontSize(8)
    }
    const shade = idx % 2 === 0 ? 255 : 249
    doc.setFillColor(shade, shade, shade)
    doc.rect(MARGIN, y, colW, ROW_H, "F")
    doc.setTextColor(40, 40, 40)

    doc.text(shortDate(d.date), cols[0].x + 1, y + 5)
    doc.text((d.notes ?? "—").slice(0, 70), cols[1].x + 1, y + 5)
    doc.text(pdfINR(Number(d.amount)), cols[2].x + cols[2].w - 1, y + 5, { align: "right" })

    total += Number(d.amount)
    y += ROW_H
  })

  drawTotalRow(doc, y, colW, "Total", pdfINR(total))
  drawFooter(doc)
  doc.save(safeFileName(loan.name, "Disbursements"))
}

/** Emerald-tinted total row spanning the table width (label left, amount right). */
function drawTotalRow(doc: jsPDF, y: number, colW: number, label: string, amount: string) {
  if (y > 270) {
    doc.addPage()
    y = 14
  }
  doc.setFillColor(220, 240, 225)
  doc.rect(MARGIN, y, colW, 8, "F")
  doc.setFont("helvetica", "bold")
  doc.setFontSize(9)
  doc.setTextColor(20, 80, 40)
  doc.text(label, MARGIN + 1, y + 5.5)
  doc.text(amount, MARGIN + colW - 1, y + 5.5, { align: "right" })
}
